### PR TITLE
Fixed new serviceprincipal layout

### PR DESCRIPTION
**Pull request by bjompen**

### CODE REVIEW

**Comment by bjompen** [comment]
refers to #2

**Comment by Ba4bes** [comment]
Hi Bjorn,
Thank you for finding and fixing these bugs!
This are updates that are part of the new Az.Resources module, which has breaking changes.
It's very helpful you have already found a fix!

Could you add one thing?
I want to make sure the module keeps working for people who might not have updated yet. So what I think we could do, is put an if-loop around the bugfixes.
So that would be something like this:
```PowerShell
if ((Get-Module Az.Resources).Version.Major -lt 5){
    $PlainTextSecret = $ServicePrincipal.PasswordCredentials.SecretText
}
else {
*the old solution
}
```
To make this work for the appId, it could be defined in a variable before $Body is created.

Do you have time to add that? If so I will merge the PR and update the module in the Gallery 👍

**Comment by bjompen** [comment]
No problem, glad to help.
Fixed check for installed version and set variables according to your requests.

**Comment by Ba4bes** [comment]
Awesome!
I tested it on PowerShell 5.1 with the old module and it all worked. So LGTM!
Once it is merged I will update the manifest and upload it to the gallery. Thank you again!

**Pull request merged**
